

table GSCL_CONNECTED_CMD {
	seq: int;
}


table CLLG_AUTH_REQ
{
	seq: int;
	accountID: string;
	password: string;
}

table CLLG_AUTH_ACK {
	seq: int;
	result: EResultID;
	accountToken: string;
	sessionKey: string;
}


table CLGS_CONNECT_REQ_ {
	seq: int;
	accounttoken: string;
	reconnect: bool;
	connectSessionKey: string;
}

table CLGS_CONNECT_ACK_ {
	seq: int;
	result: int;
}

table CLGS_AUTHEN_REQ {
	seq: int;
	accounttoken: string;
	reconnect: bool;
	connectSessionKey: string;
}

table CLGS_AUTHEN_ACK {
	seq: int;
	result: EResultID;
}

