// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PROTOCOID_H_
#define FLATBUFFERS_GENERATED_PROTOCOID_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

struct CLGS_AUTHEN_REQ;
struct CLGS_AUTHEN_REQBuilder;
struct CLGS_AUTHEN_REQT;

struct CLGS_AUTHEN_ACK;
struct CLGS_AUTHEN_ACKBuilder;
struct CLGS_AUTHEN_ACKT;

struct DBGS_Authentication_REQ;
struct DBGS_Authentication_REQBuilder;
struct DBGS_Authentication_REQT;

struct F_GUEST_MESSAGE_MIN;
struct F_GUEST_MESSAGE_MINBuilder;
struct F_GUEST_MESSAGE_MINT;

struct F_GUEST_MESSAGE_MAX;
struct F_GUEST_MESSAGE_MAXBuilder;
struct F_GUEST_MESSAGE_MAXT;

struct F_MEMBER_MESSAGE_MIN;
struct F_MEMBER_MESSAGE_MINBuilder;
struct F_MEMBER_MESSAGE_MINT;

struct F_MEMBER_MESSAGE_MAX;
struct F_MEMBER_MESSAGE_MAXBuilder;
struct F_MEMBER_MESSAGE_MAXT;

struct S_SERVER_MESSAGE_MIN;
struct S_SERVER_MESSAGE_MINBuilder;
struct S_SERVER_MESSAGE_MINT;

struct S_SERVER_MESSAGE_MAX;
struct S_SERVER_MESSAGE_MAXBuilder;
struct S_SERVER_MESSAGE_MAXT;

struct P_SERVER_MESSAGE_MIN;
struct P_SERVER_MESSAGE_MINBuilder;
struct P_SERVER_MESSAGE_MINT;

struct P_SERVER_MESSAGE_MAX;
struct P_SERVER_MESSAGE_MAXBuilder;
struct P_SERVER_MESSAGE_MAXT;

struct MessageHolder;
struct MessageHolderBuilder;
struct MessageHolderT;

inline const ::flatbuffers::TypeTable *CLGS_AUTHEN_REQTypeTable();

inline const ::flatbuffers::TypeTable *CLGS_AUTHEN_ACKTypeTable();

inline const ::flatbuffers::TypeTable *DBGS_Authentication_REQTypeTable();

inline const ::flatbuffers::TypeTable *F_GUEST_MESSAGE_MINTypeTable();

inline const ::flatbuffers::TypeTable *F_GUEST_MESSAGE_MAXTypeTable();

inline const ::flatbuffers::TypeTable *F_MEMBER_MESSAGE_MINTypeTable();

inline const ::flatbuffers::TypeTable *F_MEMBER_MESSAGE_MAXTypeTable();

inline const ::flatbuffers::TypeTable *S_SERVER_MESSAGE_MINTypeTable();

inline const ::flatbuffers::TypeTable *S_SERVER_MESSAGE_MAXTypeTable();

inline const ::flatbuffers::TypeTable *P_SERVER_MESSAGE_MINTypeTable();

inline const ::flatbuffers::TypeTable *P_SERVER_MESSAGE_MAXTypeTable();

inline const ::flatbuffers::TypeTable *MessageHolderTypeTable();

enum class EDefineID : int32_t {
  E_UNKNOWN = 0,
  E_UNKNOWN_DEFINE = 1,
  E_ITEM_MAX_COUNT = 1000
};

inline const EDefineID (&EnumValuesEDefineID())[3] {
  static const EDefineID values[] = {
    EDefineID::E_UNKNOWN,
    EDefineID::E_UNKNOWN_DEFINE,
    EDefineID::E_ITEM_MAX_COUNT
  };
  return values;
}

inline const char *EnumNameEDefineID(EDefineID e) {
  switch (e) {
    case EDefineID::E_UNKNOWN: return "E_UNKNOWN";
    case EDefineID::E_UNKNOWN_DEFINE: return "E_UNKNOWN_DEFINE";
    case EDefineID::E_ITEM_MAX_COUNT: return "E_ITEM_MAX_COUNT";
    default: return "";
  }
}

enum class MessageID : int32_t {
  NONE = 0,
  F_GUEST_MESSAGE_MIN = 1,
  CLGS_AUTHEN_REQ = 41,
  CLGS_AUTHEN_ACK = 42,
  DBGS_Authentication_REQ = 43,
  F_MEMBER_MESSAGE_MAX = 19999
};

inline const MessageID (&EnumValuesMessageID())[6] {
  static const MessageID values[] = {
    MessageID::NONE,
    MessageID::F_GUEST_MESSAGE_MIN,
    MessageID::CLGS_AUTHEN_REQ,
    MessageID::CLGS_AUTHEN_ACK,
    MessageID::DBGS_Authentication_REQ,
    MessageID::F_MEMBER_MESSAGE_MAX
  };
  return values;
}

inline const char *EnumNameMessageID(MessageID e) {
  switch (e) {
    case MessageID::NONE: return "NONE";
    case MessageID::F_GUEST_MESSAGE_MIN: return "F_GUEST_MESSAGE_MIN";
    case MessageID::CLGS_AUTHEN_REQ: return "CLGS_AUTHEN_REQ";
    case MessageID::CLGS_AUTHEN_ACK: return "CLGS_AUTHEN_ACK";
    case MessageID::DBGS_Authentication_REQ: return "DBGS_Authentication_REQ";
    case MessageID::F_MEMBER_MESSAGE_MAX: return "F_MEMBER_MESSAGE_MAX";
    default: return "";
  }
}

template<typename T> struct MessageIDTraits {
  static const MessageID enum_value = MessageID::NONE;
};

template<> struct MessageIDTraits<F_GUEST_MESSAGE_MIN> {
  static const MessageID enum_value = MessageID::F_GUEST_MESSAGE_MIN;
};

template<> struct MessageIDTraits<CLGS_AUTHEN_REQ> {
  static const MessageID enum_value = MessageID::CLGS_AUTHEN_REQ;
};

template<> struct MessageIDTraits<CLGS_AUTHEN_ACK> {
  static const MessageID enum_value = MessageID::CLGS_AUTHEN_ACK;
};

template<> struct MessageIDTraits<DBGS_Authentication_REQ> {
  static const MessageID enum_value = MessageID::DBGS_Authentication_REQ;
};

template<> struct MessageIDTraits<F_MEMBER_MESSAGE_MAX> {
  static const MessageID enum_value = MessageID::F_MEMBER_MESSAGE_MAX;
};

template<typename T> struct MessageIDUnionTraits {
  static const MessageID enum_value = MessageID::NONE;
};

template<> struct MessageIDUnionTraits<F_GUEST_MESSAGE_MINT> {
  static const MessageID enum_value = MessageID::F_GUEST_MESSAGE_MIN;
};

template<> struct MessageIDUnionTraits<CLGS_AUTHEN_REQT> {
  static const MessageID enum_value = MessageID::CLGS_AUTHEN_REQ;
};

template<> struct MessageIDUnionTraits<CLGS_AUTHEN_ACKT> {
  static const MessageID enum_value = MessageID::CLGS_AUTHEN_ACK;
};

template<> struct MessageIDUnionTraits<DBGS_Authentication_REQT> {
  static const MessageID enum_value = MessageID::DBGS_Authentication_REQ;
};

template<> struct MessageIDUnionTraits<F_MEMBER_MESSAGE_MAXT> {
  static const MessageID enum_value = MessageID::F_MEMBER_MESSAGE_MAX;
};

struct MessageIDUnion {
  MessageID type;
  void *value;

  MessageIDUnion() : type(MessageID::NONE), value(nullptr) {}
  MessageIDUnion(MessageIDUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(MessageID::NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  MessageIDUnion(const MessageIDUnion &);
  MessageIDUnion &operator=(const MessageIDUnion &u)
    { MessageIDUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  MessageIDUnion &operator=(MessageIDUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~MessageIDUnion() { Reset(); }

  void Reset();

  template <typename T>
  void Set(T&& val) {
    typedef typename std::remove_reference<T>::type RT;
    Reset();
    type = MessageIDUnionTraits<RT>::enum_value;
    if (type != MessageID::NONE) {
      value = new RT(std::forward<T>(val));
    }
  }

  static void *UnPack(const void *obj, MessageID type, const ::flatbuffers::resolver_function_t *resolver);
  ::flatbuffers::Offset<void> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  F_GUEST_MESSAGE_MINT *AsF_GUEST_MESSAGE_MIN() {
    return type == MessageID::F_GUEST_MESSAGE_MIN ?
      reinterpret_cast<F_GUEST_MESSAGE_MINT *>(value) : nullptr;
  }
  const F_GUEST_MESSAGE_MINT *AsF_GUEST_MESSAGE_MIN() const {
    return type == MessageID::F_GUEST_MESSAGE_MIN ?
      reinterpret_cast<const F_GUEST_MESSAGE_MINT *>(value) : nullptr;
  }
  CLGS_AUTHEN_REQT *AsCLGS_AUTHEN_REQ() {
    return type == MessageID::CLGS_AUTHEN_REQ ?
      reinterpret_cast<CLGS_AUTHEN_REQT *>(value) : nullptr;
  }
  const CLGS_AUTHEN_REQT *AsCLGS_AUTHEN_REQ() const {
    return type == MessageID::CLGS_AUTHEN_REQ ?
      reinterpret_cast<const CLGS_AUTHEN_REQT *>(value) : nullptr;
  }
  CLGS_AUTHEN_ACKT *AsCLGS_AUTHEN_ACK() {
    return type == MessageID::CLGS_AUTHEN_ACK ?
      reinterpret_cast<CLGS_AUTHEN_ACKT *>(value) : nullptr;
  }
  const CLGS_AUTHEN_ACKT *AsCLGS_AUTHEN_ACK() const {
    return type == MessageID::CLGS_AUTHEN_ACK ?
      reinterpret_cast<const CLGS_AUTHEN_ACKT *>(value) : nullptr;
  }
  DBGS_Authentication_REQT *AsDBGS_Authentication_REQ() {
    return type == MessageID::DBGS_Authentication_REQ ?
      reinterpret_cast<DBGS_Authentication_REQT *>(value) : nullptr;
  }
  const DBGS_Authentication_REQT *AsDBGS_Authentication_REQ() const {
    return type == MessageID::DBGS_Authentication_REQ ?
      reinterpret_cast<const DBGS_Authentication_REQT *>(value) : nullptr;
  }
  F_MEMBER_MESSAGE_MAXT *AsF_MEMBER_MESSAGE_MAX() {
    return type == MessageID::F_MEMBER_MESSAGE_MAX ?
      reinterpret_cast<F_MEMBER_MESSAGE_MAXT *>(value) : nullptr;
  }
  const F_MEMBER_MESSAGE_MAXT *AsF_MEMBER_MESSAGE_MAX() const {
    return type == MessageID::F_MEMBER_MESSAGE_MAX ?
      reinterpret_cast<const F_MEMBER_MESSAGE_MAXT *>(value) : nullptr;
  }
};

bool VerifyMessageID(::flatbuffers::Verifier &verifier, const void *obj, MessageID type);
bool VerifyMessageIDVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<MessageID> *types);

struct CLGS_AUTHEN_REQT : public ::flatbuffers::NativeTable {
  typedef CLGS_AUTHEN_REQ TableType;
  int32_t seq = 0;
  std::string accounttoken{};
  bool reconnect = false;
  std::string connectSessionKey{};
};

struct CLGS_AUTHEN_REQ FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CLGS_AUTHEN_REQT NativeTableType;
  typedef CLGS_AUTHEN_REQBuilder Builder;
  struct Traits;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return CLGS_AUTHEN_REQTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SEQ = 4,
    VT_ACCOUNTTOKEN = 6,
    VT_RECONNECT = 8,
    VT_CONNECTSESSIONKEY = 10
  };
  int32_t seq() const {
    return GetField<int32_t>(VT_SEQ, 0);
  }
  const ::flatbuffers::String *accounttoken() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACCOUNTTOKEN);
  }
  bool reconnect() const {
    return GetField<uint8_t>(VT_RECONNECT, 0) != 0;
  }
  const ::flatbuffers::String *connectSessionKey() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONNECTSESSIONKEY);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_SEQ, 4) &&
           VerifyOffset(verifier, VT_ACCOUNTTOKEN) &&
           verifier.VerifyString(accounttoken()) &&
           VerifyField<uint8_t>(verifier, VT_RECONNECT, 1) &&
           VerifyOffset(verifier, VT_CONNECTSESSIONKEY) &&
           verifier.VerifyString(connectSessionKey()) &&
           verifier.EndTable();
  }
  CLGS_AUTHEN_REQT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CLGS_AUTHEN_REQT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CLGS_AUTHEN_REQ> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CLGS_AUTHEN_REQT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CLGS_AUTHEN_REQBuilder {
  typedef CLGS_AUTHEN_REQ Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_seq(int32_t seq) {
    fbb_.AddElement<int32_t>(CLGS_AUTHEN_REQ::VT_SEQ, seq, 0);
  }
  void add_accounttoken(::flatbuffers::Offset<::flatbuffers::String> accounttoken) {
    fbb_.AddOffset(CLGS_AUTHEN_REQ::VT_ACCOUNTTOKEN, accounttoken);
  }
  void add_reconnect(bool reconnect) {
    fbb_.AddElement<uint8_t>(CLGS_AUTHEN_REQ::VT_RECONNECT, static_cast<uint8_t>(reconnect), 0);
  }
  void add_connectSessionKey(::flatbuffers::Offset<::flatbuffers::String> connectSessionKey) {
    fbb_.AddOffset(CLGS_AUTHEN_REQ::VT_CONNECTSESSIONKEY, connectSessionKey);
  }
  explicit CLGS_AUTHEN_REQBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CLGS_AUTHEN_REQ> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CLGS_AUTHEN_REQ>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CLGS_AUTHEN_REQ> CreateCLGS_AUTHEN_REQ(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t seq = 0,
    ::flatbuffers::Offset<::flatbuffers::String> accounttoken = 0,
    bool reconnect = false,
    ::flatbuffers::Offset<::flatbuffers::String> connectSessionKey = 0) {
  CLGS_AUTHEN_REQBuilder builder_(_fbb);
  builder_.add_connectSessionKey(connectSessionKey);
  builder_.add_accounttoken(accounttoken);
  builder_.add_seq(seq);
  builder_.add_reconnect(reconnect);
  return builder_.Finish();
}

struct CLGS_AUTHEN_REQ::Traits {
  using type = CLGS_AUTHEN_REQ;
  static auto constexpr Create = CreateCLGS_AUTHEN_REQ;
};

inline ::flatbuffers::Offset<CLGS_AUTHEN_REQ> CreateCLGS_AUTHEN_REQDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t seq = 0,
    const char *accounttoken = nullptr,
    bool reconnect = false,
    const char *connectSessionKey = nullptr) {
  auto accounttoken__ = accounttoken ? _fbb.CreateString(accounttoken) : 0;
  auto connectSessionKey__ = connectSessionKey ? _fbb.CreateString(connectSessionKey) : 0;
  return CreateCLGS_AUTHEN_REQ(
      _fbb,
      seq,
      accounttoken__,
      reconnect,
      connectSessionKey__);
}

::flatbuffers::Offset<CLGS_AUTHEN_REQ> CreateCLGS_AUTHEN_REQ(::flatbuffers::FlatBufferBuilder &_fbb, const CLGS_AUTHEN_REQT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct CLGS_AUTHEN_ACKT : public ::flatbuffers::NativeTable {
  typedef CLGS_AUTHEN_ACK TableType;
  int32_t seq = 0;
  int32_t result = 0;
};

struct CLGS_AUTHEN_ACK FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CLGS_AUTHEN_ACKT NativeTableType;
  typedef CLGS_AUTHEN_ACKBuilder Builder;
  struct Traits;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return CLGS_AUTHEN_ACKTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SEQ = 4,
    VT_RESULT = 6
  };
  int32_t seq() const {
    return GetField<int32_t>(VT_SEQ, 0);
  }
  int32_t result() const {
    return GetField<int32_t>(VT_RESULT, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_SEQ, 4) &&
           VerifyField<int32_t>(verifier, VT_RESULT, 4) &&
           verifier.EndTable();
  }
  CLGS_AUTHEN_ACKT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(CLGS_AUTHEN_ACKT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<CLGS_AUTHEN_ACK> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CLGS_AUTHEN_ACKT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct CLGS_AUTHEN_ACKBuilder {
  typedef CLGS_AUTHEN_ACK Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_seq(int32_t seq) {
    fbb_.AddElement<int32_t>(CLGS_AUTHEN_ACK::VT_SEQ, seq, 0);
  }
  void add_result(int32_t result) {
    fbb_.AddElement<int32_t>(CLGS_AUTHEN_ACK::VT_RESULT, result, 0);
  }
  explicit CLGS_AUTHEN_ACKBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CLGS_AUTHEN_ACK> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CLGS_AUTHEN_ACK>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CLGS_AUTHEN_ACK> CreateCLGS_AUTHEN_ACK(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t seq = 0,
    int32_t result = 0) {
  CLGS_AUTHEN_ACKBuilder builder_(_fbb);
  builder_.add_result(result);
  builder_.add_seq(seq);
  return builder_.Finish();
}

struct CLGS_AUTHEN_ACK::Traits {
  using type = CLGS_AUTHEN_ACK;
  static auto constexpr Create = CreateCLGS_AUTHEN_ACK;
};

::flatbuffers::Offset<CLGS_AUTHEN_ACK> CreateCLGS_AUTHEN_ACK(::flatbuffers::FlatBufferBuilder &_fbb, const CLGS_AUTHEN_ACKT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct DBGS_Authentication_REQT : public ::flatbuffers::NativeTable {
  typedef DBGS_Authentication_REQ TableType;
  int32_t seq = 0;
  int32_t sessionID = 0;
  std::string accountToken{};
  bool reconnect = false;
  std::string connectSessionKey{};
};

struct DBGS_Authentication_REQ FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DBGS_Authentication_REQT NativeTableType;
  typedef DBGS_Authentication_REQBuilder Builder;
  struct Traits;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return DBGS_Authentication_REQTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SEQ = 4,
    VT_SESSIONID = 6,
    VT_ACCOUNTTOKEN = 8,
    VT_RECONNECT = 10,
    VT_CONNECTSESSIONKEY = 12
  };
  int32_t seq() const {
    return GetField<int32_t>(VT_SEQ, 0);
  }
  int32_t sessionID() const {
    return GetField<int32_t>(VT_SESSIONID, 0);
  }
  const ::flatbuffers::String *accountToken() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACCOUNTTOKEN);
  }
  bool reconnect() const {
    return GetField<uint8_t>(VT_RECONNECT, 0) != 0;
  }
  const ::flatbuffers::String *connectSessionKey() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONNECTSESSIONKEY);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_SEQ, 4) &&
           VerifyField<int32_t>(verifier, VT_SESSIONID, 4) &&
           VerifyOffset(verifier, VT_ACCOUNTTOKEN) &&
           verifier.VerifyString(accountToken()) &&
           VerifyField<uint8_t>(verifier, VT_RECONNECT, 1) &&
           VerifyOffset(verifier, VT_CONNECTSESSIONKEY) &&
           verifier.VerifyString(connectSessionKey()) &&
           verifier.EndTable();
  }
  DBGS_Authentication_REQT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(DBGS_Authentication_REQT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<DBGS_Authentication_REQ> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DBGS_Authentication_REQT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct DBGS_Authentication_REQBuilder {
  typedef DBGS_Authentication_REQ Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_seq(int32_t seq) {
    fbb_.AddElement<int32_t>(DBGS_Authentication_REQ::VT_SEQ, seq, 0);
  }
  void add_sessionID(int32_t sessionID) {
    fbb_.AddElement<int32_t>(DBGS_Authentication_REQ::VT_SESSIONID, sessionID, 0);
  }
  void add_accountToken(::flatbuffers::Offset<::flatbuffers::String> accountToken) {
    fbb_.AddOffset(DBGS_Authentication_REQ::VT_ACCOUNTTOKEN, accountToken);
  }
  void add_reconnect(bool reconnect) {
    fbb_.AddElement<uint8_t>(DBGS_Authentication_REQ::VT_RECONNECT, static_cast<uint8_t>(reconnect), 0);
  }
  void add_connectSessionKey(::flatbuffers::Offset<::flatbuffers::String> connectSessionKey) {
    fbb_.AddOffset(DBGS_Authentication_REQ::VT_CONNECTSESSIONKEY, connectSessionKey);
  }
  explicit DBGS_Authentication_REQBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DBGS_Authentication_REQ> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DBGS_Authentication_REQ>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DBGS_Authentication_REQ> CreateDBGS_Authentication_REQ(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t seq = 0,
    int32_t sessionID = 0,
    ::flatbuffers::Offset<::flatbuffers::String> accountToken = 0,
    bool reconnect = false,
    ::flatbuffers::Offset<::flatbuffers::String> connectSessionKey = 0) {
  DBGS_Authentication_REQBuilder builder_(_fbb);
  builder_.add_connectSessionKey(connectSessionKey);
  builder_.add_accountToken(accountToken);
  builder_.add_sessionID(sessionID);
  builder_.add_seq(seq);
  builder_.add_reconnect(reconnect);
  return builder_.Finish();
}

struct DBGS_Authentication_REQ::Traits {
  using type = DBGS_Authentication_REQ;
  static auto constexpr Create = CreateDBGS_Authentication_REQ;
};

inline ::flatbuffers::Offset<DBGS_Authentication_REQ> CreateDBGS_Authentication_REQDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t seq = 0,
    int32_t sessionID = 0,
    const char *accountToken = nullptr,
    bool reconnect = false,
    const char *connectSessionKey = nullptr) {
  auto accountToken__ = accountToken ? _fbb.CreateString(accountToken) : 0;
  auto connectSessionKey__ = connectSessionKey ? _fbb.CreateString(connectSessionKey) : 0;
  return CreateDBGS_Authentication_REQ(
      _fbb,
      seq,
      sessionID,
      accountToken__,
      reconnect,
      connectSessionKey__);
}

::flatbuffers::Offset<DBGS_Authentication_REQ> CreateDBGS_Authentication_REQ(::flatbuffers::FlatBufferBuilder &_fbb, const DBGS_Authentication_REQT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct F_GUEST_MESSAGE_MINT : public ::flatbuffers::NativeTable {
  typedef F_GUEST_MESSAGE_MIN TableType;
};

struct F_GUEST_MESSAGE_MIN FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef F_GUEST_MESSAGE_MINT NativeTableType;
  typedef F_GUEST_MESSAGE_MINBuilder Builder;
  struct Traits;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return F_GUEST_MESSAGE_MINTypeTable();
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  F_GUEST_MESSAGE_MINT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(F_GUEST_MESSAGE_MINT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<F_GUEST_MESSAGE_MIN> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const F_GUEST_MESSAGE_MINT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct F_GUEST_MESSAGE_MINBuilder {
  typedef F_GUEST_MESSAGE_MIN Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit F_GUEST_MESSAGE_MINBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<F_GUEST_MESSAGE_MIN> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<F_GUEST_MESSAGE_MIN>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<F_GUEST_MESSAGE_MIN> CreateF_GUEST_MESSAGE_MIN(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  F_GUEST_MESSAGE_MINBuilder builder_(_fbb);
  return builder_.Finish();
}

struct F_GUEST_MESSAGE_MIN::Traits {
  using type = F_GUEST_MESSAGE_MIN;
  static auto constexpr Create = CreateF_GUEST_MESSAGE_MIN;
};

::flatbuffers::Offset<F_GUEST_MESSAGE_MIN> CreateF_GUEST_MESSAGE_MIN(::flatbuffers::FlatBufferBuilder &_fbb, const F_GUEST_MESSAGE_MINT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct F_GUEST_MESSAGE_MAXT : public ::flatbuffers::NativeTable {
  typedef F_GUEST_MESSAGE_MAX TableType;
};

struct F_GUEST_MESSAGE_MAX FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef F_GUEST_MESSAGE_MAXT NativeTableType;
  typedef F_GUEST_MESSAGE_MAXBuilder Builder;
  struct Traits;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return F_GUEST_MESSAGE_MAXTypeTable();
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  F_GUEST_MESSAGE_MAXT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(F_GUEST_MESSAGE_MAXT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<F_GUEST_MESSAGE_MAX> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const F_GUEST_MESSAGE_MAXT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct F_GUEST_MESSAGE_MAXBuilder {
  typedef F_GUEST_MESSAGE_MAX Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit F_GUEST_MESSAGE_MAXBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<F_GUEST_MESSAGE_MAX> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<F_GUEST_MESSAGE_MAX>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<F_GUEST_MESSAGE_MAX> CreateF_GUEST_MESSAGE_MAX(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  F_GUEST_MESSAGE_MAXBuilder builder_(_fbb);
  return builder_.Finish();
}

struct F_GUEST_MESSAGE_MAX::Traits {
  using type = F_GUEST_MESSAGE_MAX;
  static auto constexpr Create = CreateF_GUEST_MESSAGE_MAX;
};

::flatbuffers::Offset<F_GUEST_MESSAGE_MAX> CreateF_GUEST_MESSAGE_MAX(::flatbuffers::FlatBufferBuilder &_fbb, const F_GUEST_MESSAGE_MAXT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct F_MEMBER_MESSAGE_MINT : public ::flatbuffers::NativeTable {
  typedef F_MEMBER_MESSAGE_MIN TableType;
};

struct F_MEMBER_MESSAGE_MIN FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef F_MEMBER_MESSAGE_MINT NativeTableType;
  typedef F_MEMBER_MESSAGE_MINBuilder Builder;
  struct Traits;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return F_MEMBER_MESSAGE_MINTypeTable();
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  F_MEMBER_MESSAGE_MINT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(F_MEMBER_MESSAGE_MINT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<F_MEMBER_MESSAGE_MIN> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const F_MEMBER_MESSAGE_MINT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct F_MEMBER_MESSAGE_MINBuilder {
  typedef F_MEMBER_MESSAGE_MIN Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit F_MEMBER_MESSAGE_MINBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<F_MEMBER_MESSAGE_MIN> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<F_MEMBER_MESSAGE_MIN>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<F_MEMBER_MESSAGE_MIN> CreateF_MEMBER_MESSAGE_MIN(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  F_MEMBER_MESSAGE_MINBuilder builder_(_fbb);
  return builder_.Finish();
}

struct F_MEMBER_MESSAGE_MIN::Traits {
  using type = F_MEMBER_MESSAGE_MIN;
  static auto constexpr Create = CreateF_MEMBER_MESSAGE_MIN;
};

::flatbuffers::Offset<F_MEMBER_MESSAGE_MIN> CreateF_MEMBER_MESSAGE_MIN(::flatbuffers::FlatBufferBuilder &_fbb, const F_MEMBER_MESSAGE_MINT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct F_MEMBER_MESSAGE_MAXT : public ::flatbuffers::NativeTable {
  typedef F_MEMBER_MESSAGE_MAX TableType;
};

struct F_MEMBER_MESSAGE_MAX FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef F_MEMBER_MESSAGE_MAXT NativeTableType;
  typedef F_MEMBER_MESSAGE_MAXBuilder Builder;
  struct Traits;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return F_MEMBER_MESSAGE_MAXTypeTable();
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  F_MEMBER_MESSAGE_MAXT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(F_MEMBER_MESSAGE_MAXT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<F_MEMBER_MESSAGE_MAX> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const F_MEMBER_MESSAGE_MAXT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct F_MEMBER_MESSAGE_MAXBuilder {
  typedef F_MEMBER_MESSAGE_MAX Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit F_MEMBER_MESSAGE_MAXBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<F_MEMBER_MESSAGE_MAX> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<F_MEMBER_MESSAGE_MAX>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<F_MEMBER_MESSAGE_MAX> CreateF_MEMBER_MESSAGE_MAX(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  F_MEMBER_MESSAGE_MAXBuilder builder_(_fbb);
  return builder_.Finish();
}

struct F_MEMBER_MESSAGE_MAX::Traits {
  using type = F_MEMBER_MESSAGE_MAX;
  static auto constexpr Create = CreateF_MEMBER_MESSAGE_MAX;
};

::flatbuffers::Offset<F_MEMBER_MESSAGE_MAX> CreateF_MEMBER_MESSAGE_MAX(::flatbuffers::FlatBufferBuilder &_fbb, const F_MEMBER_MESSAGE_MAXT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct S_SERVER_MESSAGE_MINT : public ::flatbuffers::NativeTable {
  typedef S_SERVER_MESSAGE_MIN TableType;
};

struct S_SERVER_MESSAGE_MIN FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef S_SERVER_MESSAGE_MINT NativeTableType;
  typedef S_SERVER_MESSAGE_MINBuilder Builder;
  struct Traits;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return S_SERVER_MESSAGE_MINTypeTable();
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  S_SERVER_MESSAGE_MINT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(S_SERVER_MESSAGE_MINT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<S_SERVER_MESSAGE_MIN> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S_SERVER_MESSAGE_MINT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct S_SERVER_MESSAGE_MINBuilder {
  typedef S_SERVER_MESSAGE_MIN Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit S_SERVER_MESSAGE_MINBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<S_SERVER_MESSAGE_MIN> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<S_SERVER_MESSAGE_MIN>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<S_SERVER_MESSAGE_MIN> CreateS_SERVER_MESSAGE_MIN(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  S_SERVER_MESSAGE_MINBuilder builder_(_fbb);
  return builder_.Finish();
}

struct S_SERVER_MESSAGE_MIN::Traits {
  using type = S_SERVER_MESSAGE_MIN;
  static auto constexpr Create = CreateS_SERVER_MESSAGE_MIN;
};

::flatbuffers::Offset<S_SERVER_MESSAGE_MIN> CreateS_SERVER_MESSAGE_MIN(::flatbuffers::FlatBufferBuilder &_fbb, const S_SERVER_MESSAGE_MINT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct S_SERVER_MESSAGE_MAXT : public ::flatbuffers::NativeTable {
  typedef S_SERVER_MESSAGE_MAX TableType;
};

struct S_SERVER_MESSAGE_MAX FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef S_SERVER_MESSAGE_MAXT NativeTableType;
  typedef S_SERVER_MESSAGE_MAXBuilder Builder;
  struct Traits;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return S_SERVER_MESSAGE_MAXTypeTable();
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  S_SERVER_MESSAGE_MAXT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(S_SERVER_MESSAGE_MAXT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<S_SERVER_MESSAGE_MAX> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S_SERVER_MESSAGE_MAXT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct S_SERVER_MESSAGE_MAXBuilder {
  typedef S_SERVER_MESSAGE_MAX Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit S_SERVER_MESSAGE_MAXBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<S_SERVER_MESSAGE_MAX> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<S_SERVER_MESSAGE_MAX>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<S_SERVER_MESSAGE_MAX> CreateS_SERVER_MESSAGE_MAX(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  S_SERVER_MESSAGE_MAXBuilder builder_(_fbb);
  return builder_.Finish();
}

struct S_SERVER_MESSAGE_MAX::Traits {
  using type = S_SERVER_MESSAGE_MAX;
  static auto constexpr Create = CreateS_SERVER_MESSAGE_MAX;
};

::flatbuffers::Offset<S_SERVER_MESSAGE_MAX> CreateS_SERVER_MESSAGE_MAX(::flatbuffers::FlatBufferBuilder &_fbb, const S_SERVER_MESSAGE_MAXT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct P_SERVER_MESSAGE_MINT : public ::flatbuffers::NativeTable {
  typedef P_SERVER_MESSAGE_MIN TableType;
};

struct P_SERVER_MESSAGE_MIN FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef P_SERVER_MESSAGE_MINT NativeTableType;
  typedef P_SERVER_MESSAGE_MINBuilder Builder;
  struct Traits;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return P_SERVER_MESSAGE_MINTypeTable();
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  P_SERVER_MESSAGE_MINT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(P_SERVER_MESSAGE_MINT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<P_SERVER_MESSAGE_MIN> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const P_SERVER_MESSAGE_MINT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct P_SERVER_MESSAGE_MINBuilder {
  typedef P_SERVER_MESSAGE_MIN Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit P_SERVER_MESSAGE_MINBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<P_SERVER_MESSAGE_MIN> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<P_SERVER_MESSAGE_MIN>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<P_SERVER_MESSAGE_MIN> CreateP_SERVER_MESSAGE_MIN(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  P_SERVER_MESSAGE_MINBuilder builder_(_fbb);
  return builder_.Finish();
}

struct P_SERVER_MESSAGE_MIN::Traits {
  using type = P_SERVER_MESSAGE_MIN;
  static auto constexpr Create = CreateP_SERVER_MESSAGE_MIN;
};

::flatbuffers::Offset<P_SERVER_MESSAGE_MIN> CreateP_SERVER_MESSAGE_MIN(::flatbuffers::FlatBufferBuilder &_fbb, const P_SERVER_MESSAGE_MINT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct P_SERVER_MESSAGE_MAXT : public ::flatbuffers::NativeTable {
  typedef P_SERVER_MESSAGE_MAX TableType;
};

struct P_SERVER_MESSAGE_MAX FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef P_SERVER_MESSAGE_MAXT NativeTableType;
  typedef P_SERVER_MESSAGE_MAXBuilder Builder;
  struct Traits;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return P_SERVER_MESSAGE_MAXTypeTable();
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
  P_SERVER_MESSAGE_MAXT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(P_SERVER_MESSAGE_MAXT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<P_SERVER_MESSAGE_MAX> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const P_SERVER_MESSAGE_MAXT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct P_SERVER_MESSAGE_MAXBuilder {
  typedef P_SERVER_MESSAGE_MAX Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  explicit P_SERVER_MESSAGE_MAXBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<P_SERVER_MESSAGE_MAX> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<P_SERVER_MESSAGE_MAX>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<P_SERVER_MESSAGE_MAX> CreateP_SERVER_MESSAGE_MAX(
    ::flatbuffers::FlatBufferBuilder &_fbb) {
  P_SERVER_MESSAGE_MAXBuilder builder_(_fbb);
  return builder_.Finish();
}

struct P_SERVER_MESSAGE_MAX::Traits {
  using type = P_SERVER_MESSAGE_MAX;
  static auto constexpr Create = CreateP_SERVER_MESSAGE_MAX;
};

::flatbuffers::Offset<P_SERVER_MESSAGE_MAX> CreateP_SERVER_MESSAGE_MAX(::flatbuffers::FlatBufferBuilder &_fbb, const P_SERVER_MESSAGE_MAXT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct MessageHolderT : public ::flatbuffers::NativeTable {
  typedef MessageHolder TableType;
  MessageIDUnion message{};
};

struct MessageHolder FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MessageHolderT NativeTableType;
  typedef MessageHolderBuilder Builder;
  struct Traits;
  static const ::flatbuffers::TypeTable *MiniReflectTypeTable() {
    return MessageHolderTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MESSAGE_TYPE = 4,
    VT_MESSAGE = 6
  };
  MessageID message_type() const {
    return static_cast<MessageID>(GetField<int32_t>(VT_MESSAGE_TYPE, 0));
  }
  const void *message() const {
    return GetPointer<const void *>(VT_MESSAGE);
  }
  template<typename T> const T *message_as() const;
  const F_GUEST_MESSAGE_MIN *message_as_F_GUEST_MESSAGE_MIN() const {
    return message_type() == MessageID::F_GUEST_MESSAGE_MIN ? static_cast<const F_GUEST_MESSAGE_MIN *>(message()) : nullptr;
  }
  const CLGS_AUTHEN_REQ *message_as_CLGS_AUTHEN_REQ() const {
    return message_type() == MessageID::CLGS_AUTHEN_REQ ? static_cast<const CLGS_AUTHEN_REQ *>(message()) : nullptr;
  }
  const CLGS_AUTHEN_ACK *message_as_CLGS_AUTHEN_ACK() const {
    return message_type() == MessageID::CLGS_AUTHEN_ACK ? static_cast<const CLGS_AUTHEN_ACK *>(message()) : nullptr;
  }
  const DBGS_Authentication_REQ *message_as_DBGS_Authentication_REQ() const {
    return message_type() == MessageID::DBGS_Authentication_REQ ? static_cast<const DBGS_Authentication_REQ *>(message()) : nullptr;
  }
  const F_MEMBER_MESSAGE_MAX *message_as_F_MEMBER_MESSAGE_MAX() const {
    return message_type() == MessageID::F_MEMBER_MESSAGE_MAX ? static_cast<const F_MEMBER_MESSAGE_MAX *>(message()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_MESSAGE_TYPE, 1) &&
           VerifyOffset(verifier, VT_MESSAGE) &&
           VerifyMessageID(verifier, message(), message_type()) &&
           verifier.EndTable();
  }
  MessageHolderT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MessageHolderT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<MessageHolder> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MessageHolderT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const F_GUEST_MESSAGE_MIN *MessageHolder::message_as<F_GUEST_MESSAGE_MIN>() const {
  return message_as_F_GUEST_MESSAGE_MIN();
}

template<> inline const CLGS_AUTHEN_REQ *MessageHolder::message_as<CLGS_AUTHEN_REQ>() const {
  return message_as_CLGS_AUTHEN_REQ();
}

template<> inline const CLGS_AUTHEN_ACK *MessageHolder::message_as<CLGS_AUTHEN_ACK>() const {
  return message_as_CLGS_AUTHEN_ACK();
}

template<> inline const DBGS_Authentication_REQ *MessageHolder::message_as<DBGS_Authentication_REQ>() const {
  return message_as_DBGS_Authentication_REQ();
}

template<> inline const F_MEMBER_MESSAGE_MAX *MessageHolder::message_as<F_MEMBER_MESSAGE_MAX>() const {
  return message_as_F_MEMBER_MESSAGE_MAX();
}

struct MessageHolderBuilder {
  typedef MessageHolder Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_message_type(MessageID message_type) {
    fbb_.AddElement<int32_t>(MessageHolder::VT_MESSAGE_TYPE, static_cast<int32_t>(message_type), 0);
  }
  void add_message(::flatbuffers::Offset<void> message) {
    fbb_.AddOffset(MessageHolder::VT_MESSAGE, message);
  }
  explicit MessageHolderBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MessageHolder> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MessageHolder>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MessageHolder> CreateMessageHolder(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    MessageID message_type = MessageID::NONE,
    ::flatbuffers::Offset<void> message = 0) {
  MessageHolderBuilder builder_(_fbb);
  builder_.add_message(message);
  builder_.add_message_type(message_type);
  return builder_.Finish();
}

struct MessageHolder::Traits {
  using type = MessageHolder;
  static auto constexpr Create = CreateMessageHolder;
};

::flatbuffers::Offset<MessageHolder> CreateMessageHolder(::flatbuffers::FlatBufferBuilder &_fbb, const MessageHolderT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline CLGS_AUTHEN_REQT *CLGS_AUTHEN_REQ::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<CLGS_AUTHEN_REQT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CLGS_AUTHEN_REQ::UnPackTo(CLGS_AUTHEN_REQT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = seq(); _o->seq = _e; }
  { auto _e = accounttoken(); if (_e) _o->accounttoken = _e->str(); }
  { auto _e = reconnect(); _o->reconnect = _e; }
  { auto _e = connectSessionKey(); if (_e) _o->connectSessionKey = _e->str(); }
}

inline ::flatbuffers::Offset<CLGS_AUTHEN_REQ> CLGS_AUTHEN_REQ::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CLGS_AUTHEN_REQT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCLGS_AUTHEN_REQ(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CLGS_AUTHEN_REQ> CreateCLGS_AUTHEN_REQ(::flatbuffers::FlatBufferBuilder &_fbb, const CLGS_AUTHEN_REQT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CLGS_AUTHEN_REQT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _seq = _o->seq;
  auto _accounttoken = _o->accounttoken.empty() ? 0 : _fbb.CreateString(_o->accounttoken);
  auto _reconnect = _o->reconnect;
  auto _connectSessionKey = _o->connectSessionKey.empty() ? 0 : _fbb.CreateString(_o->connectSessionKey);
  return CreateCLGS_AUTHEN_REQ(
      _fbb,
      _seq,
      _accounttoken,
      _reconnect,
      _connectSessionKey);
}

inline CLGS_AUTHEN_ACKT *CLGS_AUTHEN_ACK::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<CLGS_AUTHEN_ACKT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void CLGS_AUTHEN_ACK::UnPackTo(CLGS_AUTHEN_ACKT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = seq(); _o->seq = _e; }
  { auto _e = result(); _o->result = _e; }
}

inline ::flatbuffers::Offset<CLGS_AUTHEN_ACK> CLGS_AUTHEN_ACK::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const CLGS_AUTHEN_ACKT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateCLGS_AUTHEN_ACK(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<CLGS_AUTHEN_ACK> CreateCLGS_AUTHEN_ACK(::flatbuffers::FlatBufferBuilder &_fbb, const CLGS_AUTHEN_ACKT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const CLGS_AUTHEN_ACKT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _seq = _o->seq;
  auto _result = _o->result;
  return CreateCLGS_AUTHEN_ACK(
      _fbb,
      _seq,
      _result);
}

inline DBGS_Authentication_REQT *DBGS_Authentication_REQ::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<DBGS_Authentication_REQT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void DBGS_Authentication_REQ::UnPackTo(DBGS_Authentication_REQT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = seq(); _o->seq = _e; }
  { auto _e = sessionID(); _o->sessionID = _e; }
  { auto _e = accountToken(); if (_e) _o->accountToken = _e->str(); }
  { auto _e = reconnect(); _o->reconnect = _e; }
  { auto _e = connectSessionKey(); if (_e) _o->connectSessionKey = _e->str(); }
}

inline ::flatbuffers::Offset<DBGS_Authentication_REQ> DBGS_Authentication_REQ::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const DBGS_Authentication_REQT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateDBGS_Authentication_REQ(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<DBGS_Authentication_REQ> CreateDBGS_Authentication_REQ(::flatbuffers::FlatBufferBuilder &_fbb, const DBGS_Authentication_REQT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const DBGS_Authentication_REQT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _seq = _o->seq;
  auto _sessionID = _o->sessionID;
  auto _accountToken = _o->accountToken.empty() ? 0 : _fbb.CreateString(_o->accountToken);
  auto _reconnect = _o->reconnect;
  auto _connectSessionKey = _o->connectSessionKey.empty() ? 0 : _fbb.CreateString(_o->connectSessionKey);
  return CreateDBGS_Authentication_REQ(
      _fbb,
      _seq,
      _sessionID,
      _accountToken,
      _reconnect,
      _connectSessionKey);
}

inline F_GUEST_MESSAGE_MINT *F_GUEST_MESSAGE_MIN::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<F_GUEST_MESSAGE_MINT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void F_GUEST_MESSAGE_MIN::UnPackTo(F_GUEST_MESSAGE_MINT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline ::flatbuffers::Offset<F_GUEST_MESSAGE_MIN> F_GUEST_MESSAGE_MIN::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const F_GUEST_MESSAGE_MINT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateF_GUEST_MESSAGE_MIN(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<F_GUEST_MESSAGE_MIN> CreateF_GUEST_MESSAGE_MIN(::flatbuffers::FlatBufferBuilder &_fbb, const F_GUEST_MESSAGE_MINT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const F_GUEST_MESSAGE_MINT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return CreateF_GUEST_MESSAGE_MIN(
      _fbb);
}

inline F_GUEST_MESSAGE_MAXT *F_GUEST_MESSAGE_MAX::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<F_GUEST_MESSAGE_MAXT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void F_GUEST_MESSAGE_MAX::UnPackTo(F_GUEST_MESSAGE_MAXT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline ::flatbuffers::Offset<F_GUEST_MESSAGE_MAX> F_GUEST_MESSAGE_MAX::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const F_GUEST_MESSAGE_MAXT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateF_GUEST_MESSAGE_MAX(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<F_GUEST_MESSAGE_MAX> CreateF_GUEST_MESSAGE_MAX(::flatbuffers::FlatBufferBuilder &_fbb, const F_GUEST_MESSAGE_MAXT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const F_GUEST_MESSAGE_MAXT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return CreateF_GUEST_MESSAGE_MAX(
      _fbb);
}

inline F_MEMBER_MESSAGE_MINT *F_MEMBER_MESSAGE_MIN::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<F_MEMBER_MESSAGE_MINT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void F_MEMBER_MESSAGE_MIN::UnPackTo(F_MEMBER_MESSAGE_MINT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline ::flatbuffers::Offset<F_MEMBER_MESSAGE_MIN> F_MEMBER_MESSAGE_MIN::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const F_MEMBER_MESSAGE_MINT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateF_MEMBER_MESSAGE_MIN(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<F_MEMBER_MESSAGE_MIN> CreateF_MEMBER_MESSAGE_MIN(::flatbuffers::FlatBufferBuilder &_fbb, const F_MEMBER_MESSAGE_MINT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const F_MEMBER_MESSAGE_MINT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return CreateF_MEMBER_MESSAGE_MIN(
      _fbb);
}

inline F_MEMBER_MESSAGE_MAXT *F_MEMBER_MESSAGE_MAX::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<F_MEMBER_MESSAGE_MAXT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void F_MEMBER_MESSAGE_MAX::UnPackTo(F_MEMBER_MESSAGE_MAXT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline ::flatbuffers::Offset<F_MEMBER_MESSAGE_MAX> F_MEMBER_MESSAGE_MAX::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const F_MEMBER_MESSAGE_MAXT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateF_MEMBER_MESSAGE_MAX(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<F_MEMBER_MESSAGE_MAX> CreateF_MEMBER_MESSAGE_MAX(::flatbuffers::FlatBufferBuilder &_fbb, const F_MEMBER_MESSAGE_MAXT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const F_MEMBER_MESSAGE_MAXT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return CreateF_MEMBER_MESSAGE_MAX(
      _fbb);
}

inline S_SERVER_MESSAGE_MINT *S_SERVER_MESSAGE_MIN::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<S_SERVER_MESSAGE_MINT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void S_SERVER_MESSAGE_MIN::UnPackTo(S_SERVER_MESSAGE_MINT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline ::flatbuffers::Offset<S_SERVER_MESSAGE_MIN> S_SERVER_MESSAGE_MIN::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S_SERVER_MESSAGE_MINT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateS_SERVER_MESSAGE_MIN(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<S_SERVER_MESSAGE_MIN> CreateS_SERVER_MESSAGE_MIN(::flatbuffers::FlatBufferBuilder &_fbb, const S_SERVER_MESSAGE_MINT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const S_SERVER_MESSAGE_MINT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return CreateS_SERVER_MESSAGE_MIN(
      _fbb);
}

inline S_SERVER_MESSAGE_MAXT *S_SERVER_MESSAGE_MAX::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<S_SERVER_MESSAGE_MAXT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void S_SERVER_MESSAGE_MAX::UnPackTo(S_SERVER_MESSAGE_MAXT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline ::flatbuffers::Offset<S_SERVER_MESSAGE_MAX> S_SERVER_MESSAGE_MAX::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const S_SERVER_MESSAGE_MAXT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateS_SERVER_MESSAGE_MAX(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<S_SERVER_MESSAGE_MAX> CreateS_SERVER_MESSAGE_MAX(::flatbuffers::FlatBufferBuilder &_fbb, const S_SERVER_MESSAGE_MAXT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const S_SERVER_MESSAGE_MAXT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return CreateS_SERVER_MESSAGE_MAX(
      _fbb);
}

inline P_SERVER_MESSAGE_MINT *P_SERVER_MESSAGE_MIN::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<P_SERVER_MESSAGE_MINT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void P_SERVER_MESSAGE_MIN::UnPackTo(P_SERVER_MESSAGE_MINT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline ::flatbuffers::Offset<P_SERVER_MESSAGE_MIN> P_SERVER_MESSAGE_MIN::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const P_SERVER_MESSAGE_MINT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateP_SERVER_MESSAGE_MIN(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<P_SERVER_MESSAGE_MIN> CreateP_SERVER_MESSAGE_MIN(::flatbuffers::FlatBufferBuilder &_fbb, const P_SERVER_MESSAGE_MINT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const P_SERVER_MESSAGE_MINT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return CreateP_SERVER_MESSAGE_MIN(
      _fbb);
}

inline P_SERVER_MESSAGE_MAXT *P_SERVER_MESSAGE_MAX::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<P_SERVER_MESSAGE_MAXT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void P_SERVER_MESSAGE_MAX::UnPackTo(P_SERVER_MESSAGE_MAXT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
}

inline ::flatbuffers::Offset<P_SERVER_MESSAGE_MAX> P_SERVER_MESSAGE_MAX::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const P_SERVER_MESSAGE_MAXT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateP_SERVER_MESSAGE_MAX(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<P_SERVER_MESSAGE_MAX> CreateP_SERVER_MESSAGE_MAX(::flatbuffers::FlatBufferBuilder &_fbb, const P_SERVER_MESSAGE_MAXT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const P_SERVER_MESSAGE_MAXT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  return CreateP_SERVER_MESSAGE_MAX(
      _fbb);
}

inline MessageHolderT *MessageHolder::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::make_unique<MessageHolderT>();
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void MessageHolder::UnPackTo(MessageHolderT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = message_type(); _o->message.type = _e; }
  { auto _e = message(); if (_e) _o->message.value = MessageIDUnion::UnPack(_e, message_type(), _resolver); }
}

inline ::flatbuffers::Offset<MessageHolder> MessageHolder::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const MessageHolderT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateMessageHolder(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<MessageHolder> CreateMessageHolder(::flatbuffers::FlatBufferBuilder &_fbb, const MessageHolderT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const MessageHolderT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _message_type = _o->message.type;
  auto _message = _o->message.Pack(_fbb);
  return CreateMessageHolder(
      _fbb,
      _message_type,
      _message);
}

inline bool VerifyMessageID(::flatbuffers::Verifier &verifier, const void *obj, MessageID type) {
  switch (type) {
    case MessageID::NONE: {
      return true;
    }
    case MessageID::F_GUEST_MESSAGE_MIN: {
      auto ptr = reinterpret_cast<const F_GUEST_MESSAGE_MIN *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageID::CLGS_AUTHEN_REQ: {
      auto ptr = reinterpret_cast<const CLGS_AUTHEN_REQ *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageID::CLGS_AUTHEN_ACK: {
      auto ptr = reinterpret_cast<const CLGS_AUTHEN_ACK *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageID::DBGS_Authentication_REQ: {
      auto ptr = reinterpret_cast<const DBGS_Authentication_REQ *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case MessageID::F_MEMBER_MESSAGE_MAX: {
      auto ptr = reinterpret_cast<const F_MEMBER_MESSAGE_MAX *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyMessageIDVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<MessageID> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyMessageID(
        verifier,  values->Get(i), types->GetEnum<MessageID>(i))) {
      return false;
    }
  }
  return true;
}

inline void *MessageIDUnion::UnPack(const void *obj, MessageID type, const ::flatbuffers::resolver_function_t *resolver) {
  (void)resolver;
  switch (type) {
    case MessageID::F_GUEST_MESSAGE_MIN: {
      auto ptr = reinterpret_cast<const F_GUEST_MESSAGE_MIN *>(obj);
      return ptr->UnPack(resolver);
    }
    case MessageID::CLGS_AUTHEN_REQ: {
      auto ptr = reinterpret_cast<const CLGS_AUTHEN_REQ *>(obj);
      return ptr->UnPack(resolver);
    }
    case MessageID::CLGS_AUTHEN_ACK: {
      auto ptr = reinterpret_cast<const CLGS_AUTHEN_ACK *>(obj);
      return ptr->UnPack(resolver);
    }
    case MessageID::DBGS_Authentication_REQ: {
      auto ptr = reinterpret_cast<const DBGS_Authentication_REQ *>(obj);
      return ptr->UnPack(resolver);
    }
    case MessageID::F_MEMBER_MESSAGE_MAX: {
      auto ptr = reinterpret_cast<const F_MEMBER_MESSAGE_MAX *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline ::flatbuffers::Offset<void> MessageIDUnion::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ::flatbuffers::rehasher_function_t *_rehasher) const {
  (void)_rehasher;
  switch (type) {
    case MessageID::F_GUEST_MESSAGE_MIN: {
      auto ptr = reinterpret_cast<const F_GUEST_MESSAGE_MINT *>(value);
      return CreateF_GUEST_MESSAGE_MIN(_fbb, ptr, _rehasher).Union();
    }
    case MessageID::CLGS_AUTHEN_REQ: {
      auto ptr = reinterpret_cast<const CLGS_AUTHEN_REQT *>(value);
      return CreateCLGS_AUTHEN_REQ(_fbb, ptr, _rehasher).Union();
    }
    case MessageID::CLGS_AUTHEN_ACK: {
      auto ptr = reinterpret_cast<const CLGS_AUTHEN_ACKT *>(value);
      return CreateCLGS_AUTHEN_ACK(_fbb, ptr, _rehasher).Union();
    }
    case MessageID::DBGS_Authentication_REQ: {
      auto ptr = reinterpret_cast<const DBGS_Authentication_REQT *>(value);
      return CreateDBGS_Authentication_REQ(_fbb, ptr, _rehasher).Union();
    }
    case MessageID::F_MEMBER_MESSAGE_MAX: {
      auto ptr = reinterpret_cast<const F_MEMBER_MESSAGE_MAXT *>(value);
      return CreateF_MEMBER_MESSAGE_MAX(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline MessageIDUnion::MessageIDUnion(const MessageIDUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case MessageID::F_GUEST_MESSAGE_MIN: {
      value = new F_GUEST_MESSAGE_MINT(*reinterpret_cast<F_GUEST_MESSAGE_MINT *>(u.value));
      break;
    }
    case MessageID::CLGS_AUTHEN_REQ: {
      value = new CLGS_AUTHEN_REQT(*reinterpret_cast<CLGS_AUTHEN_REQT *>(u.value));
      break;
    }
    case MessageID::CLGS_AUTHEN_ACK: {
      value = new CLGS_AUTHEN_ACKT(*reinterpret_cast<CLGS_AUTHEN_ACKT *>(u.value));
      break;
    }
    case MessageID::DBGS_Authentication_REQ: {
      value = new DBGS_Authentication_REQT(*reinterpret_cast<DBGS_Authentication_REQT *>(u.value));
      break;
    }
    case MessageID::F_MEMBER_MESSAGE_MAX: {
      value = new F_MEMBER_MESSAGE_MAXT(*reinterpret_cast<F_MEMBER_MESSAGE_MAXT *>(u.value));
      break;
    }
    default:
      break;
  }
}

inline void MessageIDUnion::Reset() {
  switch (type) {
    case MessageID::F_GUEST_MESSAGE_MIN: {
      auto ptr = reinterpret_cast<F_GUEST_MESSAGE_MINT *>(value);
      delete ptr;
      break;
    }
    case MessageID::CLGS_AUTHEN_REQ: {
      auto ptr = reinterpret_cast<CLGS_AUTHEN_REQT *>(value);
      delete ptr;
      break;
    }
    case MessageID::CLGS_AUTHEN_ACK: {
      auto ptr = reinterpret_cast<CLGS_AUTHEN_ACKT *>(value);
      delete ptr;
      break;
    }
    case MessageID::DBGS_Authentication_REQ: {
      auto ptr = reinterpret_cast<DBGS_Authentication_REQT *>(value);
      delete ptr;
      break;
    }
    case MessageID::F_MEMBER_MESSAGE_MAX: {
      auto ptr = reinterpret_cast<F_MEMBER_MESSAGE_MAXT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = MessageID::NONE;
}

inline const ::flatbuffers::TypeTable *EDefineIDTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_INT, 0, 0 },
    { ::flatbuffers::ET_INT, 0, 0 },
    { ::flatbuffers::ET_INT, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    EDefineIDTypeTable
  };
  static const int64_t values[] = { 0, 1, 1000 };
  static const char * const names[] = {
    "E_UNKNOWN",
    "E_UNKNOWN_DEFINE",
    "E_ITEM_MAX_COUNT"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_ENUM, 3, type_codes, type_refs, nullptr, values, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *MessageIDTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_SEQUENCE, 0, -1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 },
    { ::flatbuffers::ET_SEQUENCE, 0, 1 },
    { ::flatbuffers::ET_SEQUENCE, 0, 2 },
    { ::flatbuffers::ET_SEQUENCE, 0, 3 },
    { ::flatbuffers::ET_SEQUENCE, 0, 4 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    F_GUEST_MESSAGE_MINTypeTable,
    CLGS_AUTHEN_REQTypeTable,
    CLGS_AUTHEN_ACKTypeTable,
    DBGS_Authentication_REQTypeTable,
    F_MEMBER_MESSAGE_MAXTypeTable
  };
  static const int64_t values[] = { 0, 1, 41, 42, 43, 19999 };
  static const char * const names[] = {
    "NONE",
    "F_GUEST_MESSAGE_MIN",
    "CLGS_AUTHEN_REQ",
    "CLGS_AUTHEN_ACK",
    "DBGS_Authentication_REQ",
    "F_MEMBER_MESSAGE_MAX"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_UNION, 6, type_codes, type_refs, nullptr, values, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *CLGS_AUTHEN_REQTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_INT, 0, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_BOOL, 0, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 }
  };
  static const char * const names[] = {
    "seq",
    "accounttoken",
    "reconnect",
    "connectSessionKey"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 4, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *CLGS_AUTHEN_ACKTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_INT, 0, -1 },
    { ::flatbuffers::ET_INT, 0, -1 }
  };
  static const char * const names[] = {
    "seq",
    "result"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *DBGS_Authentication_REQTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_INT, 0, -1 },
    { ::flatbuffers::ET_INT, 0, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 },
    { ::flatbuffers::ET_BOOL, 0, -1 },
    { ::flatbuffers::ET_STRING, 0, -1 }
  };
  static const char * const names[] = {
    "seq",
    "sessionID",
    "accountToken",
    "reconnect",
    "connectSessionKey"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 5, type_codes, nullptr, nullptr, nullptr, names
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *F_GUEST_MESSAGE_MINTypeTable() {
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 0, nullptr, nullptr, nullptr, nullptr, nullptr
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *F_GUEST_MESSAGE_MAXTypeTable() {
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 0, nullptr, nullptr, nullptr, nullptr, nullptr
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *F_MEMBER_MESSAGE_MINTypeTable() {
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 0, nullptr, nullptr, nullptr, nullptr, nullptr
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *F_MEMBER_MESSAGE_MAXTypeTable() {
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 0, nullptr, nullptr, nullptr, nullptr, nullptr
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *S_SERVER_MESSAGE_MINTypeTable() {
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 0, nullptr, nullptr, nullptr, nullptr, nullptr
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *S_SERVER_MESSAGE_MAXTypeTable() {
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 0, nullptr, nullptr, nullptr, nullptr, nullptr
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *P_SERVER_MESSAGE_MINTypeTable() {
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 0, nullptr, nullptr, nullptr, nullptr, nullptr
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *P_SERVER_MESSAGE_MAXTypeTable() {
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 0, nullptr, nullptr, nullptr, nullptr, nullptr
  };
  return &tt;
}

inline const ::flatbuffers::TypeTable *MessageHolderTypeTable() {
  static const ::flatbuffers::TypeCode type_codes[] = {
    { ::flatbuffers::ET_UTYPE, 0, 0 },
    { ::flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const ::flatbuffers::TypeFunction type_refs[] = {
    MessageIDTypeTable
  };
  static const char * const names[] = {
    "message_type",
    "message"
  };
  static const ::flatbuffers::TypeTable tt = {
    ::flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, nullptr, names
  };
  return &tt;
}

inline const MessageHolder *GetMessageHolder(const void *buf) {
  return ::flatbuffers::GetRoot<MessageHolder>(buf);
}

inline const MessageHolder *GetSizePrefixedMessageHolder(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<MessageHolder>(buf);
}

inline bool VerifyMessageHolderBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<MessageHolder>(nullptr);
}

inline bool VerifySizePrefixedMessageHolderBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<MessageHolder>(nullptr);
}

inline void FinishMessageHolderBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<MessageHolder> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMessageHolderBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<MessageHolder> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::shared_ptr<MessageHolderT> UnPackMessageHolder(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::shared_ptr<MessageHolderT>(GetMessageHolder(buf)->UnPack(res));
}

inline std::shared_ptr<MessageHolderT> UnPackSizePrefixedMessageHolder(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::shared_ptr<MessageHolderT>(GetSizePrefixedMessageHolder(buf)->UnPack(res));
}

#endif  // FLATBUFFERS_GENERATED_PROTOCOID_H_
